### ISSUE TITLE
Support com.gradleup.shadow

### ISSUE THREAD

**Issue by asinbow** [xpdustry/kotlin-shadow-relocator#14]
As com.github.johnrengelman.shadow has been donated to Gradle as com.gradleup.shadow, newer version of kotlin-shadow-relocator should be based on com.gradleup.shadow.
The API may be different.

**Comment by phinner** [comment]
Ok, thank you for reminding me.

> I can't believe someone else is actually using this plugin.

**Comment by phinner** [comment]
Done https://github.com/xpdustry/kotlin-shadow-relocator/releases/tag/v2.0.0.
Thanks again.
